CREATE DATABASE IF NOT EXISTS logs_db;
USE logs_db;

CREATE TABLE IF NOT EXISTS logs_auth (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nivel VARCHAR(50),
    mensaje TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs_orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nivel VARCHAR(50),
    mensaje TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
